version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: usersdb
    ports:
      - "3307:3306"
    volumes:
      - ./Backend/DataBases/Users/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - auth-net

  userauth:
    build:
      context: ./Backend/Domain/UserAuth
    container_name: userauth
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=usersdb
      - DB_PORT=3306
      - PORT=3000
    networks:
      - auth-net

  getuser-service:
    build:
      context: ./Backend/Domain/GetUser
    container_name: getuser
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=usersdb
      - DB_PORT=3306
      - PORT=3002
    networks:
      - auth-net

  updateuser-service:
    build:
      context: ./Backend/Domain/UpdateUser
    container_name: updateuser
    ports:
      - "3003:3003"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=usersdb
      - DB_PORT=3306
      - PORT=3003
    networks:
      - auth-net

  deleteuser-service:
    build:
      context: ./Backend/Domain/DeleteUser
    container_name: deleteuser
    ports:
      - "3004:3004"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=usersdb
      - DB_PORT=3306
      - PORT=3004
    networks:
      - auth-net

  userauthjwt-service:
    build:
      context: ./Backend/Domain/UserAuthentication
    container_name: userauthjwt
    ports:
      - "3005:3005"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=usersdb
      - DB_PORT=3306
      - PORT=3005
      - JWT_SECRET=supersecretkey
    networks:
      - auth-net

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - auth-net

  usernotification-service:
    build:
      context: ./Backend/Domain/UserNotification
    container_name: usernotification
    ports:
      - "3006:3006"
    depends_on:
      - redis
    environment:
      - PORT=3006
      - REDIS_URL=redis://redis:6379
    networks:
      - auth-net

volumes:
  mysql_data:

networks:
  auth-net:
    driver: bridge
