// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/quotation": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Crear una nueva cotización",
                "parameters": [
                    {
                        "description": "Quotation info",
                        "name": "quotation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Quotation"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cotización creada correctamente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/quotations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Obtener todas las cotizaciones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Quotation"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Quotation": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "clientName": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Quotation API",
	Description:      "Microservicio para manejar cotizaciones de reservas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,

}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
