basePath: /
definitions:
  main.Quotation:
    properties:
      amount:
        type: number
      clientName:
        type: string
      currency:
        type: string
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Microservicio para manejar cotizaciones de reservas
  title: Quotation API
  version: "1.0"
paths:
  /quotation:
    post:
      consumes:
      - application/json
      parameters:
      - description: Quotation info
        in: body
        name: quotation
        required: true
        schema:
          $ref: '#/definitions/main.Quotation'
      produces:
      - application/json
      responses:
        "200":
          description: Cotización creada correctamente
          schema:
            type: string
      summary: Crear una nueva cotización
  /quotations:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Quotation'
            type: array
      summary: Obtener todas las cotizaciones
swagger: "2.0"
