name: Deploy Frontend

on:
  push:
    branches:
      - test
    paths:
      - 'Frontend/**'
      - '.github/workflows/build-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t mftc2412/frontend-app ./Frontend
          docker push mftc2412/frontend-app

      - name: Deploy to EC2 Frontend Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER_FRONT }}
          key: ${{ secrets.EC2_KEY_FRONT }}
          script: |
            docker rm -f frontend-app || true
            docker pull mftc2412/frontend-app
            docker run -d --restart unless-stopped --name frontend-app -p 8080:80 mftc2412/frontend-app
